### ISSUE TITLE
Is there any visualization tool for HTA, similar to the visualization interface of tensorboard plugin?

### ISSUE THREAD

**Issue by GuWei007** [facebookresearch/HolisticTraceAnalysis#145]
### What is your question?

Is there any visualization tool for HTA, similar to the visualization interface of tensorboard plugin?

### Code

>>> kernel_type_metrics_df
                                         kernel_type     sum  percentage
0                                      COMMUNICATION  171780        61.6
1                                        COMPUTATION   83182        29.8
2              COMPUTATION overlapping COMMUNICATION   23056         8.3
3                   COMMUNICATION overlapping MEMORY     479         0.2
4                                             MEMORY     169         0.1
5  COMPUTATION overlapping COMMUNICATION overlapp...      12         0.0
6                     COMPUTATION overlapping MEMORY       2         0.0

### What have you tried?

I didn’t find any relevant documentation in the Pytorch community.

### Environment

OS (Linux ):
OS version:ubuntu2004
Python version: 3.10
HTA version: 0.2.0
How did you installed HTA (pip, source):pip

**Comment by GuWei007** [comment]
~/HolisticTraceAnalysis/examples# ipython memory_analysis_demo.ipynb
File /opt/conda/lib/python3.10/site-packages/plotly/io/_base_renderers.py:675, in open_html_in_browser(html, using, new, autoraise)
    672 browser = None
    674 if using is None:
--> 675     browser = webbrowser.get(None)
    676 else:
    677     if not isinstance(using, tuple):

File /opt/conda/lib/python3.10/webbrowser.py:65, in get(using)
     63         elif command[0] is not None:
     64             return command[0]()
---> 65 raise Error("could not locate runnable browser")

Error: could not locate runnable browser

**Comment by GuWei007** [comment]
when i use tensorboard, the param "--bind_all" solves my problem, what can i do when use HTA
tensorboard --logdir=./samples --bind_all

**Comment by briancoutinho** [comment]
@GuWei007  not too familiar with how tensorboard integrates with things, HTA was mainly written to work with ipython notebooks / plotly. @aaronenyeshi  you have any idea on tensorboard

**Comment by aaronenyeshi** [comment]
Sorry, Tensorboard Plugin has been deprecated. @GuWei007 , do you have any screenshots of what kinds of visualizations from tensorboard that you would like to propose for HTA?

**Comment by fengxizhou** [comment]
@GuWei007 Hi Wei,

HTA currently hasn't been integrated with TensorBoard yet. However, as a Python library, you can easily visualize its analysis results in Jupyter Notebook or Jupyter Lab (https://jupyter.org/).

It's possible to write a TensorBoard plugin for selected analyses by following the guidelines provided here: https://github.com/tensorflow/tensorboard/blob/master/ADDING_A_PLUGIN.md. However, creating a TensorBoard plugin is not on our top list.
