### ISSUE TITLE
comm_comp_overlap_df = analyzer.get_comm_comp_overlap()  error

### ISSUE THREAD

**Issue by cooper190113** [facebookresearch/HolisticTraceAnalysis#56]
### 🐛 Describe the bug

**1、Dependency version**
python 3.8

HolisticTraceAnalysis    0.2.0
torch                    2.0.1
torchvision              0.15.2

**2、Trace Collection Code**
[train_model.zip](https://github.com/facebookresearch/HolisticTraceAnalysis/files/11955492/train_model.zip)

**3、Test Code And Error**
![image](https://github.com/facebookresearch/HolisticTraceAnalysis/assets/851243/bd294d59-1cff-4a3f-af34-ed05ce685284)
![image](https://github.com/facebookresearch/HolisticTraceAnalysis/assets/851243/de490144-f277-42d8-8a0d-ffe3bda213d3)
![image](https://github.com/facebookresearch/HolisticTraceAnalysis/assets/851243/85f044eb-f883-4a3a-b75d-2f8cf1e0e941)

**4、Trace Log**
[k8s-master_1065184.1688527520264.pt.trace.zip](https://github.com/facebookresearch/HolisticTraceAnalysis/files/11955444/k8s-master_1065184.1688527520264.pt.trace.zip)

### Steps to reproduce

OK

### Expected behavior

OK

### Environment

python 3.8

HolisticTraceAnalysis    0.2.0
torch                    2.0.1
torchvision              0.15.2

**Comment by cooper190113** [comment]
ok

**Comment by anupambhatnagar** [comment]
@cooper190113 I'm not sure what is the behavior you are expecting here. For the communication computation overlap, HTA is returning the correct results. In the attached trace there are no NCCL kernels so the communication computation overlap is 0%, as it should be.

**Comment by anupambhatnagar** [comment]
closing the issue. feel free to re-open it if there are any problems.
