### ISSUE TITLE
Introduce Memory Analyzer feature

### ISSUE THREAD

**Issue by aaronenyeshi** [facebookresearch/HolisticTraceAnalysis#60]
### 🚀 Motivation and context

Kineto Profiler can now dump memory events, and it may make sense to piece it together with trace events for deeper analysis.

Goal: Introduce memory event information from the memory profiler into Holistic Trace Analysis, so that we can eventually build analyzers on top of memory data. 

### Description

1. Raw memory events can be collected alongside torch.profiler when enabling profile_memory=True. You can dump the raw memory events into a json file using the following function, export_memory_timeline_raw. Here is the diff: https://github.com/pytorch/pytorch/pull/105094
2. Raw event json file contains a list of entries in the form (timestamp, action, num of bytes, category). You can correlate the event to trace events using timestamp.
3. Build a plot view that shows the category memory usage over time.

For internal developers, here is a Bento Notebook that profiles and builds a plot: https://www.internalfb.com/intern/anp/view/?id=3938738

**Comment by anupambhatnagar** [comment]
@aaronenyeshi This would be a great feature to add to HTA. Thanks for providing the detailed description. Assuming we make a MemoryAnalysis class what would the API look like? Could you state the user facing functions and some ideas on testing the API.

**Comment by aaronenyeshi** [comment]
Please find attached the raw.json.gz which includes the memory events, as well the plot.
[memory_timeline.raw.json.gz](https://github.com/facebookresearch/HolisticTraceAnalysis/files/12861222/memory_timeline.raw.json.gz)
![image](https://github.com/facebookresearch/HolisticTraceAnalysis/assets/17602366/7102e218-7260-4138-ae4f-53033c82e8e8)

**Comment by anupambhatnagar** [comment]
Thanks @aaronenyeshi!

**Comment by msaroufim** [comment]
Would this also help with debugging OOMs or would it assume the program didn't crash?

**Comment by anupambhatnagar** [comment]
> Would this also help with debugging OOMs or would it assume the program didn't crash?

This assumes the program doesn't crash.

**Comment by anupambhatnagar** [comment]
@aaronenyeshi Fix timestamp from rdtsc to microseconds in the raw memory events.

**Comment by aaronenyeshi** [comment]
> @aaronenyeshi Fix timestamp from rdtsc to microseconds in the raw memory events.

The fix has landed in https://github.com/pytorch/pytorch/pull/112772. Thank you!
