### ISSUE TITLE
The regenerated json file is garbled

### ISSUE THREAD

**Issue by BadTrasher** [facebookresearch/HolisticTraceAnalysis#64]
### What is your question?

When I call "get_frequent_cuda_kernel_sequences" , The regenerated json file is garbled

### What have you tried?

I opened the json file and found that the encoding format is latin1, I tried to convert it to utf8, but it didn't work

### Environment

Linux x86_64 Ubuntu
Python version:3.8
HTA version:0.2.0
How did you installed HTA (pip, source):pip

**Comment by anupambhatnagar** [comment]
@BadTrasher Can you please share the original trace file and the one generated after you executed `get_frequent_cuda_kernel_sequences`?

**Comment by anupambhatnagar** [comment]
@BadTrasher closing the issue as it seems to be resolved. feel free to reopen, if needed.
